// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSMSVSUtils
{
    internal sealed partial class Vsix
    {
        public const string Id = "SSMSVSUtils.1eab7686-ed75-494e-8a2d-cfd4d2da1477";
        public const string Name = "SSMSVSUtils";
        public const string Description = @"VSIX SSMS & VS Utilities";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Jeff Lomax";
        public const string Tags = "";
    }
}
