// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSMSVSUtils
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SSMSVSUtilsString = "d298403f-60cc-469c-8346-4d7fa4ee9ab4";
        public static Guid SSMSVSUtils = new Guid(SSMSVSUtilsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyToolWindow = 0x0002;
        public const int HardLineDownCommand = 0x0103;
        public const int SomeTestCommand = 0x0107;
    }
}