// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourceControlDeepLinks
{
    internal sealed partial class Vsix
    {
        public const string Id = "SourceControlDeepLinks.1eab7686-ed75-494e-8a2d-cfd4d2da1477";
        public const string Name = "SourceControlDeepLinks";
        public const string Description = @"VSIX Source Control Extension for Bitbucket Server";
        public const string Language = "en-US";
        public const string Version = "0.7.9";
        public const string Author = "Jeff Lomax";
        public const string Tags = "";
    }
}
