// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourceControlDeepLinks
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SourceControlDeepLinksString = "7a6afcfd-674d-409f-9cde-4e63c1fc73c8";
        public static Guid SourceControlDeepLinks = new Guid(SourceControlDeepLinksString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyToolMenuFlyout = 0x0001;
        public const int BitbucketDeepLinkCommand = 0x0101;
        public const int BitbucketLinesDeepLinkCommand = 0x0102;
        public const int DeepLinkDynamicCommand = 0x0103;
        public const int ToolsExternalFlyoutMenu = 0x1021;
        public const int MyToolsExternalFlyoutMenuGroup = 0x1022;
        public const int BitBucketLinkMenu = 0x0200;
        public const int BitbucketMenu = 0x0201;
        public const int BitBucketMenuButton = 0x0202;
        public const int MyToolMenuFlyoutGroup = 0x0203;
    }
}