// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLSynSugarAndValidation
{
    internal sealed partial class Vsix
    {
        public const string Id = "SQLSynSugarAndValidation.1eab7686-ed75-494e-8a2d-cfd4d2da1477";
        public const string Name = "SQLSynSugarAndValidation";
        public const string Description = @"VSIX SQL Magic";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Jeff Lomax";
        public const string Tags = "";
    }
}
