// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLSynSugarAndValidation
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SQLSynSugarAndValidationString = "c5c49737-d82b-44da-819c-1763b651e9ba";
        public static Guid SQLSynSugarAndValidation = new Guid(SQLSynSugarAndValidationString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyToolWindow = 0x0002;
        public const int ExecuteStatementCommand = 0x0104;
        public const int ToolWindowCommand = 0x0105;
        public const int IntellisenseCommand = 0x0106;
    }
}