// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourceControlDeepLinks
{
  internal sealed partial class Vsix
  {
    public const string Id = "SourceControlDeepLinks.ea8550af-3db2-42ff-87f0-49af5d25b409";
    public const string Name = "SourceControlDeepLinks";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Paylocity";
    public const string Tags = "";
  }
}
