// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLPaste
{
    internal sealed partial class Vsix
    {
        public const string Id = "SQLPaste.1eab7686-ed75-494e-8a2d-cfd4d2da1477";
        public const string Name = "SQLPaste";
        public const string Description = @"VSIX Paste Extensions, CSV and Values paste";
        public const string Language = "en-US";
        public const string Version = "0.4";
        public const string Author = "Jeff Lomax";
        public const string Tags = "";
    }
}
