// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace SQLPaste
{
    internal sealed partial class Vsix
    {
        public const string Id = "SQLPaste.fbf9fd1f-db9a-4d06-bce7-6df60ec5953a";
        public const string Name = "SQLPaste";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jeff Lomax";
        public const string Tags = "";
    }
}
