// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLPaste
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SQLPasteString = "ef125253-cc0f-4086-8172-a7858313255f";
        public static Guid SQLPaste = new Guid(SQLPasteString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyPasteMenuGroup = 0x0001;
        public const int EditFlyoutMenu = 0x0123;
        public const int MyEditFlyoutMenuGroup = 0x0124;
        public const int CsvPasteCommand = 0x0100;
        public const int ValuesPasteCommand = 0x0101;
        public const int PasteOptionsCommand = 0x0102;
    }
}